name: Build and Deploy to Production

# Trigger the workflow on a push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # --- Backend Setup (Laravel) ---
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Match your project's PHP version

    - name: Install Composer Dependencies
      working-directory: ./eunixmac_backend
      run: composer install --no-dev --optimize-autoloader

    # --- Frontend Setup (React/Vite) ---
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23' # Match your project's Node version

    - name: Install NPM Dependencies
      working-directory: ./eunixmac_frontend
      run: npm install

    - name: Build Frontend Assets
      working-directory: ./eunixmac_frontend
      run: npm run build

    # --- Test SFTP Connection ---
    - name: Test SFTP Connection
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        echo "Attempting to connect to SFTP server..."
        sshpass -p "${{ secrets.SFTP_PASSWORD }}" sftp -o StrictHostKeyChecking=no -P 22 ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} <<< "ls /home/eunixmac/public_html/eunixmac_backend/"
        echo "SFTP connection test finished."

    # --- Deploy Files via SFTP ---
    - name: Deploy Backend Files
      uses: wangyucode/sftp-upload-action@v1.4.9
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 22
        local_path: ./eunixmac_backend/
        remote_path: /home/eunixmac/public_html/eunixmac_backend/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .github/**
          storage/logs/*
          .env

    - name: Deploy Frontend Files
      uses: wangyucode/sftp-upload-action@v1.4.9
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 22
        local_path: ./eunixmac_frontend/dist/
        remote_path: /home/eunixmac/public_html/eunixmac_frontend/